trigger: none

variables:
  variableGroupName: iac-versions
  artifactFeed: IaC-demo-azure-terraform
  artifactView: Prerelease
  artifactName: iac-demo-azure-terraform-package

jobs:
  #azure
  - template: templates/job-validation-template.yml

  - template: templates/job-versioning-template.yml
    parameters:
      variableGroupName: $(variableGroupName)
      sourceBranchName: $(System.PullRequest.SourceBranch)
      prereleaseAlias: preview

  - template: templates/job-publish-template.yml
    parameters:
      artifactFeed: $(artifactFeed)
      artifactView: $(artifactView)
      artifactName: $(artifactName)
